spring:
  application:
    name: xuyang-api
  profiles:
    active: local
springdoc:
  api-docs:
    enabled: true
    path: '/v3/api-docs'
  swagger-ui:
    url: '/xuyang-api/v3/api-docs'
    path: '/swagger-ui'
    config-url: '/xuyang-api/v3/api-docs/swagger-config'
argo:
  api:
    token: ${ARGO_API_TOKEN:}
server:
  servlet:
    context-path: /xuyang-api
  forward-headers-strategy: framework
